arrowParens: 'always'
singleQuote: true
jsxSingleQuote: true
bracketSpacing: true
bracketSameLine: true
semi: true
trailingComma: 'all'
useTabs: true
tabWidth: 2
endOfLine: 'lf'
printWidth: 600
proseWrap: 'never'
quoteProps: 'consistent'
singleAttributePerLine: true
vueIndentScriptAndStyle: true
experimentalTernaries: true
plugins: ['C:/Users/Maulana/AppData/Roaming/npm/node_modules/@ianvs/prettier-plugin-sort-imports/lib/src/index.js']
importOrder: ['^react$', '<TYPES>^(node:)', '<TYPES>', '<TYPES>^[.]', '<BUILT_IN_MODULES>', '<THIRD_PARTY_MODULES>', '^[.]', '^(?!.*[.]css$)[./].*$', '.css$']
